[build]
target = "targets/mips-ultra64-cpu.json"

[target.mips-ultra64-cpu]
rustflags = [
    "-C",
    "link-arg=-Ttargets/linker.ld",
    "-C",
    "link-arg=--Map=target/map",
    "-C",
    "opt-level=s",
]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
